apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-nthskyweb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-nthskyweb
  template:
    metadata:
      labels:
        app: k8s-nthskyweb
    spec:
      containers:
      - name: k8s-nthskyweb
        image: nthskyradiated/nthskyweb
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
